defaults:
  -
    scope:
      path: ""
    values:
      layout: default
description: Spencer Tiberi's Personal Website
exclude:
  - "application.py"
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "passenger_wsgi.py"
host: 0.0.0.0
port: 8080
title: Spencer Tiberi
exclude: [vendor]

theme: jekyll-theme-midnight